### ISSUE TITLE
Outputting the kernel matrix

### ISSUE THREAD

**Issue by rbardenet** [cgartrel/nonsymmetric-DPP-learning#1]
thanks for the code! Is there a simple way to output the learned kernel? I'm especially interested in outputting learned asymmetric kernels.

**Comment by cgartrel** [comment]
Currently there is no builtin support for doing this.  The easiest way to implement this would probably be to add some code after the model is trained (or loaded from disk, if previously trained), after https://github.com/cgartrel/nonsymmetric-DPP-learning/blob/94d0e65a3fc38bab2518f0341a4f7780127dbf52/src/main.py#L493.  After this line, you could call `V, B, C = model.forward(model.all_items_in_catalog_set_var)` to get the V, B, and C matrices for the nonsymmetric L kernel.  These matrices are all PyTorch tensors, which can then be easily be serialized to disk in your format of choice (Numpy arrays, CSV, etc).

**Comment by rbardenet** [comment]
Thanks a lot! I will give you feeback if we make anything interesting out of it.
